### ISSUE TITLE
Consistent threading option?

### ISSUE THREAD

**Issue by maltezfaria** [JuliaLinearAlgebra/RecursiveFactorization.jl#40]
The `thread` argument in e.g. `lu` does not propagate to `schur_complement!` (which uses `@tturbo`), so the execution is still partially threaded when `thread=Val(false)`. Is that intended?

**Comment by chriselrod** [comment]
> The `thread` argument in e.g. `lu` does not propagate to `schur_complement!` (which uses `@tturbo`), so the execution is still partially threaded when `thread=Val(false)`. Is that intended?

No, I missed that one.

**Comment by maltezfaria** [comment]
Fixed in #41
