### ISSUE TITLE
Package fails on Julia 1.6

### ISSUE THREAD

**Issue by jebej** [JuliaLinearAlgebra/RecursiveFactorization.jl#67]
It looks like a dependence on a third `LU` type parameter was introduced in commit https://github.com/JuliaLinearAlgebra/RecursiveFactorization.jl/commit/659b99b42ce02bf49e2e9f90b0225cc77b52810e

This parameter does not exist on julia 1.6, breaking the package.

```
ERROR: LoadError: LoadError: too many parameters for type
Stacktrace:
  [1] top-level scope
    @ C:\Users\jebej\.julia\packages\RecursiveFactorization\oD8uH\src\lu.jl:35 
```

**Comment by t-bltg** [comment]
Also hit this on `1.9.0-beta2`.
Should be caught by ci ? Is the workflow broken ?

cc @YingboMa.

**Comment by sathvikbhagavan** [comment]
It is also failing in 1.7.3
